import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  auth: {
    login: (credentials: any) => ipcRenderer.invoke('auth:login', credentials),
    getMe: () => ipcRenderer.invoke('auth:getMe'),
    getUsers: () => ipcRenderer.invoke('auth:getUsers'),
    logout: () => ipcRenderer.invoke('auth:logout'),
    verifyManagerPin: (data: any) => ipcRenderer.invoke('auth:verifyManagerPin', data),
    setManagerPin: (data: any) => ipcRenderer.invoke('auth:setManagerPin', data),
  },
  audit: {
    getAll: (limit?: number) => ipcRenderer.invoke('audit:getAll', limit),
    verifyIntegrity: () => ipcRenderer.invoke('audit:verifyIntegrity'),
    sealLegacy: () => ipcRenderer.invoke('audit:sealLegacy'),
  },
  products: {
    getAll: () => ipcRenderer.invoke('products:getAll'),
    getOne: (id: string) => ipcRenderer.invoke('products:getOne', id),
    create: (data: any) => ipcRenderer.invoke('products:create', data),
    update: (id: string, data: any) => ipcRenderer.invoke('products:update', id, data),
    remove: (id: string) => ipcRenderer.invoke('products:remove', id),
    stockIn: (id: string, data: any) => ipcRenderer.invoke('products:stockIn', id, data),
    getMovements: (id: string) => ipcRenderer.invoke('products:getMovements', id),
  },
  inventory: {
    getSummary: () => ipcRenderer.invoke('inventory:getSummary'),
    getLowStock: () => ipcRenderer.invoke('inventory:getLowStock'),
    getMovements: () => ipcRenderer.invoke('inventory:getMovements'),
    getValuation: () => ipcRenderer.invoke('inventory:getValuation'),
    stockIn: (id: string, data: any) => ipcRenderer.invoke('inventory:stockIn', id, data),
    stockOut: (id: string, data: any) => ipcRenderer.invoke('inventory:stockOut', id, data),
    adjustStock: (id: string, data: any) => ipcRenderer.invoke('inventory:adjustStock', id, data),
    addWastage: (id: string, data: any) => ipcRenderer.invoke('inventory:addWastage', id, data),
  },
  suppliers: {
    getAll: () => ipcRenderer.invoke('suppliers:getAll'),
    create: (data: any) => ipcRenderer.invoke('suppliers:create', data),
    update: (id: string, data: any) => ipcRenderer.invoke('suppliers:update', id, data),
    collectMilk: (data: any) => ipcRenderer.invoke('suppliers:collectMilk', data),
    collectPayment: (id: string, data: any) => ipcRenderer.invoke('suppliers:collectPayment', id, data),
    getCollections: (filters?: any) => ipcRenderer.invoke('suppliers:getCollections', filters),
    getLedger: (id: string) => ipcRenderer.invoke('suppliers:getLedger', id),
    getCycleReport: (filters: any) => ipcRenderer.invoke('suppliers:getCycleReport', filters),
    getCycleStatement: (filters: any) => ipcRenderer.invoke('suppliers:getCycleStatement', filters),
  },
  customers: {
    getAll: (filters?: any) => ipcRenderer.invoke('customers:getAll', filters),
    getOne: (id: string) => ipcRenderer.invoke('customers:getOne', id),
    create: (data: any) => ipcRenderer.invoke('customers:create', data),
    update: (id: string, data: any) => ipcRenderer.invoke('customers:update', id, data),
    remove: (id: string) => ipcRenderer.invoke('customers:remove', id),
    getLedger: (id: string) => ipcRenderer.invoke('customers:getLedger', id),
    collectPayment: (id: string, data: any) => ipcRenderer.invoke('customers:collectPayment', id, data),
    search: (query: string) => ipcRenderer.invoke('customers:search', query),
    getStatement: (id: string, startDate?: string, endDate?: string) => ipcRenderer.invoke('customers:getStatement', id, startDate, endDate),
  },
  sales: {
    create: (data: any) => ipcRenderer.invoke('sales:create', data),
    getAll: (filters?: any) => ipcRenderer.invoke('sales:getAll', filters),
    getOne: (id: string) => ipcRenderer.invoke('sales:getOne', id),
    getReceipt: (id: string) => ipcRenderer.invoke('sales:getReceipt', id),
    void: (data: any) => ipcRenderer.invoke('sales:void', data),
    hold: (data: any) => ipcRenderer.invoke('sales:hold', data),
    getHeld: () => ipcRenderer.invoke('sales:getHeld'),
    deleteHeld: (id: string) => ipcRenderer.invoke('sales:deleteHeld', id),
  },
  returns: {
    getAll: (filters?: any) => ipcRenderer.invoke('returns:getAll', filters),
    getSaleForReturn: (saleIdOrBillNumber: string) => ipcRenderer.invoke('returns:getSaleForReturn', saleIdOrBillNumber),
    create: (data: any) => ipcRenderer.invoke('returns:create', data),
  },
  receiptAudit: {
    preview: (data: any) => ipcRenderer.invoke('receiptAudit:preview', data),
    save: (data: any) => ipcRenderer.invoke('receiptAudit:save', data),
    getHistory: (limit?: number) => ipcRenderer.invoke('receiptAudit:getHistory', limit),
    getLatestForDate: (date: string) => ipcRenderer.invoke('receiptAudit:getLatestForDate', date),
  },
  expenses: {
    getAll: (filters?: any) => ipcRenderer.invoke('expenses:getAll', filters),
    create: (data: any) => ipcRenderer.invoke('expenses:create', data),
    update: (id: string, data: any) => ipcRenderer.invoke('expenses:update', id, data),
    remove: (id: string) => ipcRenderer.invoke('expenses:remove', id),
    getSummary: () => ipcRenderer.invoke('expenses:getSummary'),
  },
  reports: {
    getDailySummary: (date: string) => ipcRenderer.invoke('reports:getDailySummary', date),
    getEndOfDay: (date: string) => ipcRenderer.invoke('reports:getEndOfDay', date),
    getZReport: (date: string) => ipcRenderer.invoke('reports:getZReport', date),
    getSalesChart: (days?: number) => ipcRenderer.invoke('reports:getSalesChart', days),
    getProductPerformance: () => ipcRenderer.invoke('reports:getProductPerformance'),
    getDashboardStats: () => ipcRenderer.invoke('reports:getDashboardStats'),
    closeRegister: (data: any) => ipcRenderer.invoke('reports:closeRegister', data),
    getCustomerDues: () => ipcRenderer.invoke('reports:getCustomerDues'),
    getProfitLoss: (startDate: string, endDate: string) => ipcRenderer.invoke('reports:getProfitLoss', startDate, endDate),
    getMonthlySummary: (year: string) => ipcRenderer.invoke('reports:getMonthlySummary', year),
    exportReport: (data: any) => ipcRenderer.invoke('exports:report', data),
  },
  dailyRates: {
    getToday: () => ipcRenderer.invoke('dailyRates:getToday'),
    update: (data: any) => ipcRenderer.invoke('dailyRates:update', data),
  },
  cashRegister: {
    getToday: () => ipcRenderer.invoke('cashRegister:getToday'),
    open: (data: any) => ipcRenderer.invoke('cashRegister:open', data),
    close: (data?: any) => ipcRenderer.invoke('cashRegister:close', data),
    getHistory: () => ipcRenderer.invoke('cashRegister:getHistory'),
  },
  shifts: {
    getCurrent: () => ipcRenderer.invoke('shifts:getCurrent'),
    getToday: () => ipcRenderer.invoke('shifts:getToday'),
    open: (data: any) => ipcRenderer.invoke('shifts:open', data),
    close: (data: any) => ipcRenderer.invoke('shifts:close', data),
    getHistory: (limit?: number) => ipcRenderer.invoke('shifts:getHistory', limit),
  },
  settings: {
    getAll: () => ipcRenderer.invoke('settings:getAll'),
    update: (data: any) => ipcRenderer.invoke('settings:update', data),
  },
  sync: {
    getStatus: () => ipcRenderer.invoke('sync:getStatus'),
    syncNow: () => ipcRenderer.invoke('sync:syncNow'),
    getPendingCount: () => ipcRenderer.invoke('sync:getPendingCount'),
  },
  system: {
    backup: () => ipcRenderer.invoke('system:backup'),
    restore: () => ipcRenderer.invoke('system:restore'),
    listBackups: () => ipcRenderer.invoke('system:listBackups'),
    openBackupFolder: () => ipcRenderer.invoke('system:openBackupFolder'),
    getPaths: () => ipcRenderer.invoke('system:getPaths'),
    getBusinessDate: () => ipcRenderer.invoke('system:getBusinessDate'),
    getHealth: () => ipcRenderer.invoke('system:getHealth'),
  },
  printer: {
    getPrinters: () => ipcRenderer.invoke('printer:getPrinters'),
    printReceipt: (receiptData: any) => ipcRenderer.invoke('printer:printReceipt', receiptData),
    printStatement: (statementData: any) => ipcRenderer.invoke('printer:printStatement', statementData),
  },
  onNetworkChange: (callback: (status: 'online' | 'offline') => void) => {
    ipcRenderer.on('network-status-changed', (_event, status) => callback(status));
  },
});
