-- Add DELIVERY_OUT and DELIVERY_RETURN to StockMovementType enum
ALTER TYPE "StockMovementType" ADD VALUE IF NOT EXISTS 'DELIVERY_OUT';
ALTER TYPE "StockMovementType" ADD VALUE IF NOT EXISTS 'DELIVERY_RETURN';
