import db from '../database/db';
import { networkMonitor } from './networkMonitor';
import { fetchWithTimeout, getApiBaseUrl, getSyncHeaders } from './apiConfig';
import { getDeviceInfo } from './deviceInfo';
import { registerDeviceWithCloud } from './deviceRegistration';
import { createOutboxEntry } from './outboxHelper';
import logger from '../utils/logger';



export class SyncEngine {
  private interval: NodeJS.Timeout | null = null;
  private isSyncing = false;
  private readonly handleNetworkOnline = () => {
    console.log('Network is back online, triggering sync');
    // Always swallow the rejection — an unhandled rejection here would crash
    // the main process. The sync body has its own retry/error handling.
    this.processPendingOutbox().catch((err) => {
      logger.warn('processPendingOutbox (online trigger) failed:', err?.message || err);
    });
  };

  private getRetryDelayMs(attemptCount: number) {
    const minutes = [1, 2, 5, 15, 30, 60][Math.min(Math.max(attemptCount, 0), 5)];
    return minutes * 60 * 1000;
  }

  // Map a child outbox row to the parent it depends on, so we can re-queue
  // the parent if a child gets stuck with "Missing parent". Each entry is
  // (child table → parent table + the FK column to look up).
  private getParentReference(tableName: string, payload: any) {
    const saleId = payload?.sale_id || payload?.saleId;
    if (['sale_items', 'saleItems', 'split_payments', 'splitPayments', 'payments', 'sale_voids', 'saleVoids'].includes(tableName) && saleId) {
      return { outboxTable: 'sales', localTable: 'sales', id: String(saleId) };
    }

    // Returns reference a parent Sale via sale_id. If a Return is stuck because
    // its Sale never made it to the cloud, we need to re-queue the Sale too.
    if (['returns'].includes(tableName) && saleId) {
      return { outboxTable: 'sales', localTable: 'sales', id: String(saleId) };
    }

    const returnId = payload?.return_id || payload?.returnId;
    if (['return_items', 'returnItems'].includes(tableName) && returnId) {
      return { outboxTable: 'returns', localTable: 'returns', id: String(returnId) };
    }

    const sessionId = payload?.session_id || payload?.sessionId;
    if (['receipt_audit_entries', 'receiptAuditEntries'].includes(tableName) && sessionId) {
      return { outboxTable: 'receipt_audit_sessions', localTable: 'receipt_audit_sessions', id: String(sessionId) };
    }

    // Customer-side ledger entries reference a customer (always) and may also
    // reference a sale (when the entry was generated by a credit sale).
    const customerId = payload?.customer_id || payload?.customerId;
    if (['ledger_entries', 'ledgerEntries'].includes(tableName) && customerId) {
      return { outboxTable: 'customers', localTable: 'customers', id: String(customerId) };
    }
    if (['payments'].includes(tableName) && customerId && !saleId) {
      return { outboxTable: 'customers', localTable: 'customers', id: String(customerId) };
    }

    // Supplier-side: every milk collection / supplier payment / supplier ledger
    // entry references a supplier. If the supplier hasn't synced, re-queue it.
    const supplierId = payload?.supplier_id || payload?.supplierId;
    if (['milk_collections', 'milkCollections', 'supplier_payments', 'supplierPayments', 'supplier_ledger_entries', 'supplierLedgerEntries'].includes(tableName) && supplierId) {
      return { outboxTable: 'suppliers', localTable: 'suppliers', id: String(supplierId) };
    }

    // Cash register and expenses reference a shift.
    const shiftId = payload?.shift_id || payload?.shiftId;
    if (['cash_register', 'cashRegister', 'expenses'].includes(tableName) && shiftId) {
      return { outboxTable: 'shifts', localTable: 'shifts', id: String(shiftId) };
    }

    return null;
  }

  private requeueMissingParent(tableName: string, payload: any) {
    const parent = this.getParentReference(tableName, payload);
    if (!parent) return false;

    const existingOutbox = db.prepare(`
      UPDATE sync_outbox
      SET status = 'pending',
          attempt_count = 0,
          error_message = NULL,
          last_attempted_at = NULL
      WHERE table_name = ? AND record_id = ?
    `).run(parent.outboxTable, parent.id);

    if (existingOutbox.changes > 0) return true;

    const parentRow = db.prepare(`SELECT * FROM ${parent.localTable} WHERE id = ?`).get(parent.id);
    if (!parentRow) return false;

    createOutboxEntry(parent.outboxTable, 'INSERT', parent.id, parentRow);
    return true;
  }

  repairMissingParentsFromOutbox() {
    // Cover every child→parent dependency we know about. If a child is stuck
    // and its parent isn't in the outbox, we look up the parent in the local
    // DB and queue it. Without this, an orphan child would loop forever
    // waiting for a parent that nobody is going to push.
    const childRows = db.prepare(`
      SELECT id, table_name, payload
      FROM sync_outbox
      WHERE status IN ('pending', 'failed')
        AND table_name IN (
          'sale_items',
          'saleItems',
          'split_payments',
          'splitPayments',
          'payments',
          'sale_voids',
          'saleVoids',
          'returns',
          'return_items',
          'returnItems',
          'receipt_audit_entries',
          'receiptAuditEntries',
          'ledger_entries',
          'ledgerEntries',
          'milk_collections',
          'milkCollections',
          'supplier_payments',
          'supplierPayments',
          'supplier_ledger_entries',
          'supplierLedgerEntries',
          'cash_register',
          'cashRegister',
          'expenses'
        )
      ORDER BY created_at ASC
      LIMIT 1000
    `).all() as any[];

    let repaired = 0;
    for (const row of childRows) {
      try {
        const payload = JSON.parse(row.payload || '{}');
        if (this.requeueMissingParent(row.table_name, payload)) {
          repaired += 1;
        }
      } catch (error: any) {
        logger.warn(`Could not inspect child sync row ${row.id}: ${error?.message || error}`);
      }
    }

    if (repaired > 0) {
      logger.info(`SyncEngine requeued ${repaired} missing parent record(s) before sync.`);
    }

    return repaired;
  }

  private async refreshSyncToken(deviceId: string) {
    try {
      await registerDeviceWithCloud();
      return Boolean(getSyncHeaders(deviceId));
    } catch (error: any) {
      logger.warn('Cloud device re-registration failed:', error?.message || error);
      return false;
    }
  }

  start() {
    if (this.interval) return;
    console.log('SyncEngine started');
    this.interval = setInterval(() => {
      // Same crash protection here: setInterval doesn't catch promise
      // rejections, so without .catch a single unexpected throw kills Electron.
      this.processPendingOutbox().catch((err) => {
        logger.warn('processPendingOutbox (interval) failed:', err?.message || err);
      });
    }, 5000);
    networkMonitor.on('online', this.handleNetworkOnline);
  }

  stop() {
    if (this.interval) clearInterval(this.interval);
    this.interval = null;
    networkMonitor.off('online', this.handleNetworkOnline);
    console.log('SyncEngine stopped');
  }

  async processPendingOutbox() {
    if (this.isSyncing) return;
    if (!networkMonitor.isOnline) return;

    const apiUrl = getApiBaseUrl();
    if (!apiUrl) {
      // Skip sync only if API URL is not configured.
      return;
    }

    this.isSyncing = true;
    try {
      this.repairMissingParentsFromOutbox();

      const pendingRows = db.prepare(`
        SELECT * FROM sync_outbox 
        WHERE status = 'pending' 
        ORDER BY
          CASE table_name
            WHEN 'users' THEN 1
            WHEN 'products' THEN 2
            WHEN 'customers' THEN 3
            WHEN 'suppliers' THEN 4
            WHEN 'shifts' THEN 5
            WHEN 'cash_register' THEN 6
            WHEN 'sales' THEN 7
            WHEN 'returns' THEN 8
            WHEN 'receipt_audit_sessions' THEN 9
            WHEN 'sale_items' THEN 20
            WHEN 'split_payments' THEN 21
            WHEN 'payments' THEN 22
            WHEN 'return_items' THEN 23
            WHEN 'receipt_audit_entries' THEN 24
            ELSE 30
          END,
          created_at ASC 
        LIMIT 500
      `).all() as any[];

      const nowMs = Date.now();
      const readyRows = pendingRows
        .filter((row) => {
          if (!row.last_attempted_at) return true;
          const lastAttemptMs = new Date(row.last_attempted_at).getTime();
          if (!Number.isFinite(lastAttemptMs)) return true;
          return nowMs - lastAttemptMs >= this.getRetryDelayMs(Number(row.attempt_count || 0));
        })
        .slice(0, 25);

      if (readyRows.length === 0) {
        this.isSyncing = false;
        return;
      }

      logger.info(`SyncEngine attempting to push ${readyRows.length} outbox entries to cloud.`);


      const deviceInfo = getDeviceInfo();
      let syncHeaders = getSyncHeaders(deviceInfo.deviceId);
      if (!syncHeaders) {
        const registered = await this.refreshSyncToken(deviceInfo.deviceId);
        syncHeaders = registered ? getSyncHeaders(deviceInfo.deviceId) : null;
        if (!syncHeaders) {
          console.warn('Cloud sync skipped because this terminal is not registered.');
          this.isSyncing = false;
          return;
        }
      }

      for (const row of readyRows) {
        // Network-level error flag — if true, abort the entire batch
        let networkError = false;

        // Parse payload once outside fetch so a corrupt JSON row never crashes
        // the engine and never re-tries forever. If parse fails we mark this
        // single row as failed and move on.
        let parsedPayload: any;
        try {
          parsedPayload = JSON.parse(row.payload);
        } catch (parseErr: any) {
          logger.error(`SyncEngine outbox row ${row.id} has corrupt payload, marking failed: ${parseErr?.message}`);
          db.prepare(`UPDATE sync_outbox SET status = 'failed', error_message = ? WHERE id = ?`)
            .run(`Corrupt payload: ${parseErr?.message || parseErr}`, row.id);
          continue;
        }

        try {
          let response: Response;
          try {
            response = await fetchWithTimeout(`${apiUrl}/sync/ingest`, {
              method: 'POST',
              headers: syncHeaders as Record<string, string>,
              body: JSON.stringify({
                table: row.table_name,
                operation: row.operation,
                recordId: row.record_id,
                payload: parsedPayload,
                timestamp: row.created_at,
                device: {
                  id: deviceInfo.deviceId,
                  name: deviceInfo.deviceName,
                  terminalNumber: deviceInfo.terminalNumber
                }
              })
            }, 30000);
          } catch (fetchErr: any) {
            // fetch() itself threw — network is down or server unreachable
            networkError = true;
            throw fetchErr;
          }

          if (response.status === 401 || response.status === 403) {
            const refreshed = await this.refreshSyncToken(deviceInfo.deviceId);
            syncHeaders = refreshed ? getSyncHeaders(deviceInfo.deviceId) : null;

            if (syncHeaders) {
              response = await fetchWithTimeout(`${apiUrl}/sync/ingest`, {
                method: 'POST',
                headers: syncHeaders as Record<string, string>,
                body: JSON.stringify({
                  table: row.table_name,
                  operation: row.operation,
                  recordId: row.record_id,
                  payload: parsedPayload,
                  timestamp: row.created_at,
                  device: {
                    id: deviceInfo.deviceId,
                    name: deviceInfo.deviceName,
                    terminalNumber: deviceInfo.terminalNumber
                  }
                })
              }, 30000);
            }

            if (!syncHeaders || response.status === 401 || response.status === 403) {
              const errText = await response.text().catch(() => '');
              logger.warn(`SyncEngine got ${response.status}; aborting batch after re-registration attempt. ${errText.substring(0, 200)}`);
              db.prepare(`
                UPDATE sync_outbox
                SET attempt_count = attempt_count + 1,
                    error_message = ?,
                    last_attempted_at = datetime('now')
                WHERE id = ?
              `).run(`Auth failed (${response.status}). Check Sync Device Secret.`, row.id);
              networkError = true;
              throw new Error(`Sync auth failed (${response.status})`);
            }
          }

          if (response.ok) {
            // Server may return HTML (e.g., Nginx 502 error page styled as a
            // 200 from a misconfigured proxy). Guard the JSON parse so it
            // doesn't crash sync — treat as a row-level error and retry.
            let result: any;
            try {
              result = await response.json();
            } catch (jsonErr: any) {
              throw new Error(`Server returned non-JSON response: ${jsonErr?.message || jsonErr}`);
            }
            const action = result?.data?.action ?? result?.action;
            const reason = result?.data?.reason ?? result?.reason ?? '';

            if (action === 'skipped' && typeof reason === 'string' && reason.startsWith('Missing parent')) {
              const parentRequeued = this.requeueMissingParent(row.table_name, parsedPayload);
              // Parent not synced yet — keep pending so it retries after parent arrives
              db.prepare(`
                UPDATE sync_outbox
                SET attempt_count = attempt_count + 1,
                    error_message = ?,
                    last_attempted_at = datetime('now')
                WHERE id = ?
              `).run(parentRequeued ? `Waiting for parent: ${reason}. Parent was queued again.` : `Waiting for parent: ${reason}`, row.id);
              logger.info(`SyncEngine deferred row ${row.id} (${row.table_name}): ${reason}`);
            } else {
              db.prepare(`UPDATE sync_outbox SET status = 'synced', error_message = NULL WHERE id = ?`).run(row.id);
              logger.info(`SyncEngine synced row ${row.id} for table '${row.table_name}' (action: ${action}).`);
            }
          } else {
            // Server returned an HTTP error for this specific row — record the error and
            // continue with the next row (don't abort the batch).
            const errText = await response.text();
            if (response.status === 400 && errText.includes('Missing parent')) {
              const parentRequeued = this.requeueMissingParent(row.table_name, parsedPayload);
              db.prepare(`
                UPDATE sync_outbox
                SET status = 'pending',
                    attempt_count = attempt_count + 1,
                    error_message = ?,
                    last_attempted_at = datetime('now')
                WHERE id = ?
              `).run(parentRequeued ? `Waiting for parent: ${errText.substring(0, 240)}. Parent was queued again.` : `Waiting for parent: ${errText.substring(0, 240)}`, row.id);
              logger.info(`SyncEngine deferred row ${row.id} (${row.table_name}) after HTTP 400 missing-parent response.`);
              continue;
            }
            const errMsg = `Server Error (${response.status}): ${errText.substring(0, 300)}`;
            logger.warn(`SyncEngine server rejected row ${row.id} (${row.table_name}): ${errMsg}`);

            db.prepare(`
              UPDATE sync_outbox
              SET attempt_count = attempt_count + 1,
                  error_message = ?,
                  last_attempted_at = datetime('now')
              WHERE id = ?
            `).run(errMsg, row.id);

            const updated = db.prepare(`SELECT attempt_count FROM sync_outbox WHERE id = ?`).get(row.id) as any;
            if (updated && updated.attempt_count >= 10) {
              db.prepare(`UPDATE sync_outbox SET status = 'failed' WHERE id = ?`).run(row.id);
            }
          }

        } catch (error: any) {
          logger.warn(`SyncEngine outbox upload failed for row ${row.id}: ${error.message}`);

          db.prepare(`
            UPDATE sync_outbox
            SET attempt_count = attempt_count + 1,
                error_message = ?,
                last_attempted_at = datetime('now')
            WHERE id = ?
          `).run(error.message, row.id);

          const updated = db.prepare(`SELECT attempt_count FROM sync_outbox WHERE id = ?`).get(row.id) as any;
          if (updated && updated.attempt_count >= 10) {
            db.prepare(`UPDATE sync_outbox SET status = 'failed' WHERE id = ?`).run(row.id);
          }

          if (networkError) {
            // Network is down — no point trying the remaining rows in this batch
            break;
          }
          // Otherwise it was a row-level error — continue with next row
        }
      }
    } catch (e) {
      console.error('Critical sync engine error:', e);
    } finally {
      this.isSyncing = false;
    }
  }
}
