import db from '../database/db';
import { networkMonitor } from './networkMonitor';
import { fetchWithTimeout, getApiBaseUrl, getSyncHeaders } from './apiConfig';
import { getDeviceInfo } from './deviceInfo';
import { registerDeviceWithCloud } from './deviceRegistration';
import { createOutboxEntry } from './outboxHelper';
import logger from '../utils/logger';



export class SyncEngine {
  private interval: NodeJS.Timeout | null = null;
  private compactInterval: NodeJS.Timeout | null = null;
  private retryFailedInterval: NodeJS.Timeout | null = null;
  private isSyncing = false;
  // Last time we ran the (expensive at scale) parent-repair scan. Throttled
  // so it doesn't fire on every 5-sec cycle when there's a 10K-row backlog.
  private lastRepairAtMs = 0;
  private readonly handleNetworkOnline = () => {
    console.log('Network is back online, triggering sync');
    // Always swallow the rejection. An unhandled rejection here would crash
    // the main process. The sync body has its own retry/error handling.
    this.processPendingOutbox().catch((err) => {
      logger.warn('processPendingOutbox (online trigger) failed:', err?.message || err);
    });
  };

  private getRetryDelayMs(attemptCount: number) {
    const minutes = [1, 2, 5, 15, 30, 60][Math.min(Math.max(attemptCount, 0), 5)];
    return minutes * 60 * 1000;
  }

  // Map a child outbox row to the parent it depends on, so we can re-queue
  // the parent if a child gets stuck with "Missing parent". Each entry is
  // (child table → parent table + the FK column to look up).
  private getParentReference(tableName: string, payload: any) {
    const saleId = payload?.sale_id || payload?.saleId;
    if (['sale_items', 'saleItems', 'split_payments', 'splitPayments', 'payments', 'sale_voids', 'saleVoids'].includes(tableName) && saleId) {
      return { outboxTable: 'sales', localTable: 'sales', id: String(saleId) };
    }

    // Returns reference a parent Sale via sale_id. If a Return is stuck because
    // its Sale never made it to the cloud, we need to re-queue the Sale too.
    if (['returns'].includes(tableName) && saleId) {
      return { outboxTable: 'sales', localTable: 'sales', id: String(saleId) };
    }

    const returnId = payload?.return_id || payload?.returnId;
    if (['return_items', 'returnItems'].includes(tableName) && returnId) {
      return { outboxTable: 'returns', localTable: 'returns', id: String(returnId) };
    }

    const sessionId = payload?.session_id || payload?.sessionId;
    if (['receipt_audit_entries', 'receiptAuditEntries'].includes(tableName) && sessionId) {
      return { outboxTable: 'receipt_audit_sessions', localTable: 'receipt_audit_sessions', id: String(sessionId) };
    }

    // Customer-side ledger entries reference a customer (always) and may also
    // reference a sale (when the entry was generated by a credit sale).
    const customerId = payload?.customer_id || payload?.customerId;
    if (['ledger_entries', 'ledgerEntries'].includes(tableName) && customerId) {
      return { outboxTable: 'customers', localTable: 'customers', id: String(customerId) };
    }
    if (['payments'].includes(tableName) && customerId && !saleId) {
      return { outboxTable: 'customers', localTable: 'customers', id: String(customerId) };
    }

    // Supplier-side: every milk collection / supplier payment / supplier ledger
    // entry references a supplier. If the supplier hasn't synced, re-queue it.
    const supplierId = payload?.supplier_id || payload?.supplierId;
    if (['milk_collections', 'milkCollections', 'supplier_payments', 'supplierPayments', 'supplier_ledger_entries', 'supplierLedgerEntries'].includes(tableName) && supplierId) {
      return { outboxTable: 'suppliers', localTable: 'suppliers', id: String(supplierId) };
    }

    // Cash register and expenses reference a shift.
    const shiftId = payload?.shift_id || payload?.shiftId;
    if (['cash_register', 'cashRegister', 'expenses'].includes(tableName) && shiftId) {
      return { outboxTable: 'shifts', localTable: 'shifts', id: String(shiftId) };
    }

    return null;
  }

  private requeueMissingParent(tableName: string, payload: any) {
    const parent = this.getParentReference(tableName, payload);
    if (!parent) return false;

    const existingOutbox = db.prepare(`
      UPDATE sync_outbox
      SET status = 'pending',
          attempt_count = 0,
          error_message = NULL,
          last_attempted_at = NULL
      WHERE table_name = ? AND record_id = ?
    `).run(parent.outboxTable, parent.id);

    if (existingOutbox.changes > 0) return true;

    const parentRow = db.prepare(`SELECT * FROM ${parent.localTable} WHERE id = ?`).get(parent.id);
    if (!parentRow) return false;

    createOutboxEntry(parent.outboxTable, 'INSERT', parent.id, parentRow);
    return true;
  }

  repairMissingParentsFromOutbox() {
    // Cover every child→parent dependency we know about. If a child is stuck
    // and its parent isn't in the outbox, we look up the parent in the local
    // DB and queue it. Without this, an orphan child would loop forever
    // waiting for a parent that nobody is going to push.
    const childRows = db.prepare(`
      SELECT id, table_name, payload
      FROM sync_outbox
      WHERE status IN ('pending', 'failed')
        AND table_name IN (
          'sale_items',
          'saleItems',
          'split_payments',
          'splitPayments',
          'payments',
          'sale_voids',
          'saleVoids',
          'returns',
          'return_items',
          'returnItems',
          'receipt_audit_entries',
          'receiptAuditEntries',
          'ledger_entries',
          'ledgerEntries',
          'milk_collections',
          'milkCollections',
          'supplier_payments',
          'supplierPayments',
          'supplier_ledger_entries',
          'supplierLedgerEntries',
          'cash_register',
          'cashRegister',
          'expenses'
        )
      ORDER BY created_at ASC
      LIMIT 1000
    `).all() as any[];

    let repaired = 0;
    for (const row of childRows) {
      try {
        const payload = JSON.parse(row.payload || '{}');
        if (this.requeueMissingParent(row.table_name, payload)) {
          repaired += 1;
        }
      } catch (error: any) {
        logger.warn(`Could not inspect child sync row ${row.id}: ${error?.message || error}`);
      }
    }

    if (repaired > 0) {
      logger.info(`SyncEngine requeued ${repaired} missing parent record(s) before sync.`);
    }

    return repaired;
  }

  private async refreshSyncToken(deviceId: string) {
    try {
      await registerDeviceWithCloud();
      return Boolean(getSyncHeaders(deviceId));
    } catch (error: any) {
      logger.warn('Cloud device re-registration failed:', error?.message || error);
      return false;
    }
  }

  // Trim the outbox so it does not grow unbounded. Synced rows older than the
  // retention window are hard-deleted. They are already on the cloud; the
  // local copy is just an audit trail and we do not need to keep it. At 2K
  // walk-in receipts/day this shop generates ~14K outbox rows/day, so we
  // aggressively drop already-synced rows after 1 HOUR (was 1 day). Owner
  // hit a 21K backlog because synced rows were piling up alongside pending
  // rows and slowing every COUNT/scan query. 1 hour is enough breathing
  // room to debug a single sync issue, and aggressive enough that a busy
  // shop never carries more than ~600 synced rows.
  private compactOutbox() {
    try {
      const result = db.prepare(`
        DELETE FROM sync_outbox
        WHERE status = 'synced'
          AND datetime(COALESCE(last_attempted_at, created_at)) <= datetime('now', '-1 hour')
      `).run();
      if (result.changes > 0) {
        logger.info(`SyncEngine compacted ${result.changes} old synced outbox row(s).`);
      }
    } catch (err: any) {
      // Compaction is opportunistic. If it fails, log and keep going.
      logger.warn('Outbox compaction failed:', err?.message || err);
    }
  }

  // Auto-recover rows that hit the attempt_count cap (10) and were marked
  // 'failed'. Without this, a transient backend error or a bad token leaves
  // every affected row stuck forever — the cashier had to manually click
  // "Reset & Retry" in the Sync Configuration tab. Now any row that has
  // been in 'failed' for >30 min gets its attempt counter wiped and is
  // re-queued. Backoff still kicks in on the next try, so we don't hammer
  // a permanently-broken backend.
  private retryStuckFailedRows() {
    try {
      const result = db.prepare(`
        UPDATE sync_outbox
        SET status = 'pending',
            attempt_count = 0,
            last_attempted_at = NULL
        WHERE status = 'failed'
          AND datetime(COALESCE(last_attempted_at, created_at)) <= datetime('now', '-30 minutes')
      `).run();
      if (result.changes > 0) {
        logger.info(`SyncEngine auto-retried ${result.changes} stuck failed row(s).`);
      }
    } catch (err: any) {
      logger.warn('Auto-retry of failed rows skipped:', err?.message || err);
    }
  }

  start() {
    if (this.interval) return;
    console.log('SyncEngine started');

    // Compact the outbox once at startup so a long-offline terminal doesn't
    // start its day with 50K stale synced rows slowing down every query.
    this.compactOutbox();
    // Also recover any rows that were stuck in 'failed' from a previous run
    // (e.g. owner restarted the app the day after a backend hiccup).
    this.retryStuckFailedRows();

    this.interval = setInterval(() => {
      // Same crash protection here: setInterval doesn't catch promise
      // rejections, so without .catch a single unexpected throw kills Electron.
      this.processPendingOutbox().catch((err) => {
        logger.warn('processPendingOutbox (interval) failed:', err?.message || err);
      });
    }, 5000);

    // Compact every 5 minutes during the day. Old retention was 1 hour with
    // hourly compaction — that meant a busy 2K-bills/hour shop could see
    // ~28K synced rows pile up between compactions. 5 minutes keeps the
    // table tiny enough that even unindexed queries stay snappy.
    this.compactInterval = setInterval(() => this.compactOutbox(), 5 * 60 * 1000);

    // Recover stuck 'failed' rows every 10 minutes. A backend hiccup or
    // expired token used to leave rows permanently dead — now they retry
    // automatically once the underlying issue is resolved.
    this.retryFailedInterval = setInterval(() => this.retryStuckFailedRows(), 10 * 60 * 1000);

    networkMonitor.on('online', this.handleNetworkOnline);
  }

  stop() {
    if (this.interval) clearInterval(this.interval);
    this.interval = null;
    if (this.compactInterval) clearInterval(this.compactInterval);
    this.compactInterval = null;
    if (this.retryFailedInterval) clearInterval(this.retryFailedInterval);
    this.retryFailedInterval = null;
    networkMonitor.off('online', this.handleNetworkOnline);
    console.log('SyncEngine stopped');
  }

  // Update DB state for a single outbox row based on the server's per-row
  // response (extracted so both single and batch code paths share the logic).
  private applyRowResult(row: any, parsedPayload: any, action: string | undefined, reason: string) {
    if (action === 'skipped' && typeof reason === 'string' && reason.startsWith('Missing parent')) {
      const parentRequeued = this.requeueMissingParent(row.table_name, parsedPayload);
      db.prepare(`
        UPDATE sync_outbox
        SET attempt_count = attempt_count + 1,
            error_message = ?,
            last_attempted_at = datetime('now')
        WHERE id = ?
      `).run(parentRequeued ? `Waiting for parent: ${reason}. Parent was queued again.` : `Waiting for parent: ${reason}`, row.id);
    } else {
      db.prepare(`UPDATE sync_outbox SET status = 'synced', error_message = NULL WHERE id = ?`).run(row.id);
    }
  }

  // Push a chunk of outbox rows in one HTTP call to /sync/ingest-batch.
  // Returns:
  //   { ok: true }                      — every row was processed; DB state updated
  //   { ok: false, networkError: true } — abort the whole cycle (auth or network down)
  //   { ok: false, fallback: true }     — server didn't accept the batch; caller
  //                                        should re-process this chunk one row at a time
  private async tryBatchPush(
    rows: any[],
    apiUrl: string,
    syncHeaders: Record<string, string>,
    deviceInfo: { deviceId: string; deviceName: string; terminalNumber: number }
  ): Promise<{ ok: true } | { ok: false; networkError?: true; fallback?: true }> {
    // Build operations payload, parsing each row's JSON. Corrupt rows are
    // hard-failed up-front so they never poison the whole chunk.
    const ops: any[] = [];
    const opRows: any[] = [];   // parallel array — same index as ops, holds the outbox row
    const opPayloads: any[] = []; // parsed payloads, same index
    for (const row of rows) {
      let parsedPayload: any;
      try {
        parsedPayload = JSON.parse(row.payload);
      } catch (parseErr: any) {
        logger.error(`SyncEngine outbox row ${row.id} has corrupt payload, marking failed: ${parseErr?.message}`);
        db.prepare(`UPDATE sync_outbox SET status = 'failed', error_message = ? WHERE id = ?`)
          .run(`Corrupt payload: ${parseErr?.message || parseErr}`, row.id);
        continue;
      }
      ops.push({
        table: row.table_name,
        operation: row.operation,
        recordId: row.record_id,
        payload: parsedPayload,
        timestamp: row.created_at,
        device: {
          id: deviceInfo.deviceId,
          name: deviceInfo.deviceName,
          terminalNumber: deviceInfo.terminalNumber
        }
      });
      opRows.push(row);
      opPayloads.push(parsedPayload);
    }
    if (ops.length === 0) return { ok: true };

    let response: Response;
    try {
      response = await fetchWithTimeout(`${apiUrl}/sync/ingest-batch`, {
        method: 'POST',
        headers: syncHeaders,
        body: JSON.stringify({ operations: ops })
      }, 60000);
    } catch (fetchErr: any) {
      // Network error — caller will abort the whole cycle.
      logger.warn(`SyncEngine batch fetch failed: ${fetchErr?.message || fetchErr}`);
      return { ok: false, networkError: true };
    }

    if (response.status === 401 || response.status === 403) {
      // Auth failure — let the caller retry once with a refreshed token.
      return { ok: false, networkError: true };
    }

    // 404 likely means the deployed backend doesn't have /sync/ingest-batch yet
    // (older build). Fall back to single-row mode so the cashier isn't blocked.
    if (response.status === 404 || response.status === 405) {
      logger.warn('SyncEngine /sync/ingest-batch not available on backend; falling back to single ingest.');
      return { ok: false, fallback: true };
    }

    if (!response.ok) {
      // 4xx/5xx on the batch endpoint itself — fall back to single-row mode.
      // Per-row processing has finer-grained error handling and may reveal
      // which specific row in the batch is poisonous.
      const errText = await response.text().catch(() => '');
      logger.warn(`SyncEngine batch returned HTTP ${response.status}; falling back. ${errText.substring(0, 200)}`);
      return { ok: false, fallback: true };
    }

    let parsed: any;
    try {
      parsed = await response.json();
    } catch (jsonErr: any) {
      logger.warn(`SyncEngine batch response was not JSON; falling back. ${jsonErr?.message}`);
      return { ok: false, fallback: true };
    }
    // Backend wraps responses with { success, data: [...] }; raw responses
    // come straight as an array. Handle both.
    const results: any[] = Array.isArray(parsed?.data) ? parsed.data
      : Array.isArray(parsed) ? parsed
      : Array.isArray(parsed?.data?.results) ? parsed.data.results
      : [];

    if (results.length !== ops.length) {
      // Mismatched array — safer to fall back so we don't apply wrong
      // results to wrong rows.
      logger.warn(`SyncEngine batch returned ${results.length} results for ${ops.length} ops; falling back.`);
      return { ok: false, fallback: true };
    }

    let synced = 0;
    let deferred = 0;
    for (let i = 0; i < results.length; i++) {
      const r = results[i] || {};
      const action = r.action ?? r?.data?.action;
      const reason = String(r.reason ?? r?.data?.reason ?? '');
      if (r.success === false) {
        // Row-level failure inside the batch (rare, since backend catches
        // common Prisma errors and returns success:true). Bump the attempt
        // counter so it backs off.
        const errMsg = `Server rejected: ${reason || 'unknown error'}`;
        db.prepare(`
          UPDATE sync_outbox
          SET attempt_count = attempt_count + 1,
              error_message = ?,
              last_attempted_at = datetime('now')
          WHERE id = ?
        `).run(errMsg, opRows[i].id);
        const updated = db.prepare(`SELECT attempt_count FROM sync_outbox WHERE id = ?`).get(opRows[i].id) as any;
        if (updated && updated.attempt_count >= 10) {
          db.prepare(`UPDATE sync_outbox SET status = 'failed' WHERE id = ?`).run(opRows[i].id);
        }
      } else {
        if (action === 'skipped' && reason.startsWith('Missing parent')) {
          deferred += 1;
        } else {
          synced += 1;
        }
        this.applyRowResult(opRows[i], opPayloads[i], action, reason);
      }
    }
    logger.info(`SyncEngine batch: ${synced} synced, ${deferred} deferred (waiting parent), ${ops.length - synced - deferred} other.`);
    return { ok: true };
  }

  async processPendingOutbox() {
    if (this.isSyncing) return;
    if (!networkMonitor.isOnline) return;

    const apiUrl = getApiBaseUrl();
    if (!apiUrl) {
      // Skip sync only if API URL is not configured.
      return;
    }

    this.isSyncing = true;
    try {
      // Parent-repair scan is O(pending+failed rows) and runs lookups against
      // local tables. With 10K+ outbox rows it can take 500ms+. Run it at
      // most once every 30 sec instead of every 5 sec. Children that need
      // a parent will still be re-queued well before the cloud retry timer
      // fires (1 min minimum), so this doesn't slow recovery.
      const nowMs = Date.now();
      if (nowMs - this.lastRepairAtMs >= 30_000) {
        this.repairMissingParentsFromOutbox();
        this.lastRepairAtMs = nowMs;
      }

      const pendingRows = db.prepare(`
        SELECT * FROM sync_outbox 
        WHERE status = 'pending' 
        ORDER BY
          CASE table_name
            WHEN 'users' THEN 1
            WHEN 'products' THEN 2
            WHEN 'customers' THEN 3
            WHEN 'suppliers' THEN 4
            WHEN 'shifts' THEN 5
            WHEN 'cash_register' THEN 6
            WHEN 'sales' THEN 7
            WHEN 'returns' THEN 8
            WHEN 'receipt_audit_sessions' THEN 9
            WHEN 'sale_items' THEN 20
            WHEN 'split_payments' THEN 21
            WHEN 'payments' THEN 22
            WHEN 'return_items' THEN 23
            WHEN 'receipt_audit_entries' THEN 24
            ELSE 30
          END,
          created_at ASC
        LIMIT 2000
      `).all() as any[];

      const retryNowMs = Date.now();
      // Push up to 1000 rows per cycle. With parallel batch chunks (below)
      // a fast connection can drain ~2-4K rows/sec, so the per-cycle ceiling
      // is now mostly about not flooding the VPS with one giant burst at a
      // time. Combined with auto-rechain after a successful cycle (see end
      // of this method), even a 21K backlog drains in well under a minute.
      const readyRows = pendingRows
        .filter((row) => {
          if (!row.last_attempted_at) return true;
          const lastAttemptMs = new Date(row.last_attempted_at).getTime();
          if (!Number.isFinite(lastAttemptMs)) return true;
          return retryNowMs - lastAttemptMs >= this.getRetryDelayMs(Number(row.attempt_count || 0));
        })
        .slice(0, 1000);

      if (readyRows.length === 0) {
        this.isSyncing = false;
        return;
      }

      logger.info(`SyncEngine attempting to push ${readyRows.length} outbox entries to cloud.`);


      const deviceInfo = getDeviceInfo();
      let syncHeaders = getSyncHeaders(deviceInfo.deviceId);
      if (!syncHeaders) {
        const registered = await this.refreshSyncToken(deviceInfo.deviceId);
        syncHeaders = registered ? getSyncHeaders(deviceInfo.deviceId) : null;
        if (!syncHeaders) {
          console.warn('Cloud sync skipped because this terminal is not registered.');
          this.isSyncing = false;
          return;
        }
      }

      // Build chunks of 100 rows each. We previously sent 50 sequentially —
      // so 1000 rows took ~20 sequential HTTP roundtrips (~4 seconds at
      // 200ms/RTT). Now we POST 4 chunks in parallel, so the same 1000 rows
      // finish in ~5 roundtrips' worth of wall time (~1 second).
      const CHUNK_SIZE = 100;
      const PARALLEL_CHUNKS = 4;
      const allChunks: any[][] = [];
      for (let i = 0; i < readyRows.length; i += CHUNK_SIZE) {
        allChunks.push(readyRows.slice(i, i + CHUNK_SIZE));
      }
      let abortRemainingChunks = false;
      let useFallbackMode = false; // sticky for the rest of this cycle once set
      const fallbackChunks: any[][] = []; // chunks that need single-row fallback

      // ---- Phase 1: parallel batch push ----
      // Process waves of N concurrent batch requests until we exhaust the
      // chunks, hit a network/auth error, or the backend signals the
      // /sync/ingest-batch endpoint is missing.
      for (let i = 0; i < allChunks.length; i += PARALLEL_CHUNKS) {
        if (abortRemainingChunks || useFallbackMode) {
          // Move every remaining chunk into the fallback list so phase 2
          // picks them up instead of marking them auth-failed.
          if (useFallbackMode) {
            for (let j = i; j < allChunks.length; j++) fallbackChunks.push(allChunks[j]);
          }
          break;
        }
        const wave = allChunks.slice(i, i + PARALLEL_CHUNKS);
        const results = await Promise.all(
          wave.map((chunk) =>
            this.tryBatchPush(chunk, apiUrl, syncHeaders as Record<string, string>, deviceInfo)
              .catch((err) => {
                logger.warn(`SyncEngine batch wave member crashed: ${err?.message || err}`);
                return { ok: false, networkError: true } as { ok: false; networkError: true };
              })
          )
        );

        // Walk the wave results in order. If any reports a network/auth
        // error we try ONE token refresh, then re-run only the failed chunks
        // serially so we don't hammer the backend with another parallel burst.
        const networkFailures: any[][] = [];
        const fallbackNeeded: any[][] = [];
        for (let j = 0; j < wave.length; j++) {
          const result = results[j];
          if (result.ok) continue;
          if (result.networkError) networkFailures.push(wave[j]);
          else if (result.fallback) fallbackNeeded.push(wave[j]);
        }

        if (fallbackNeeded.length > 0) {
          // Backend doesn't support the batch endpoint — switch to
          // single-row mode for everything from here on.
          useFallbackMode = true;
          for (const chunk of fallbackNeeded) fallbackChunks.push(chunk);
          // Also push remaining un-attempted chunks
          for (let k = i + PARALLEL_CHUNKS; k < allChunks.length; k++) {
            fallbackChunks.push(allChunks[k]);
          }
          // And chunks in this wave that haven't been classified — none, but
          // be safe for any future wave changes.
          break;
        }

        if (networkFailures.length > 0) {
          // Try a single token refresh, then retry the failed chunks
          // sequentially so a transient blip doesn't poison the cycle.
          const refreshed = await this.refreshSyncToken(deviceInfo.deviceId);
          const newHeaders = refreshed ? getSyncHeaders(deviceInfo.deviceId) : null;
          if (newHeaders) {
            syncHeaders = newHeaders;
            for (const chunk of networkFailures) {
              const retry = await this.tryBatchPush(chunk, apiUrl, newHeaders, deviceInfo);
              if (retry.ok) continue;
              if (retry.fallback) {
                useFallbackMode = true;
                fallbackChunks.push(chunk);
                continue;
              }
              // Still failing — bump attempt counters and abort remaining.
              for (const row of chunk) {
                db.prepare(`
                  UPDATE sync_outbox
                  SET attempt_count = attempt_count + 1,
                      error_message = ?,
                      last_attempted_at = datetime('now')
                  WHERE id = ?
                `).run('Auth failed. Check Sync Device Secret or backend availability.', row.id);
                const updated = db.prepare(`SELECT attempt_count FROM sync_outbox WHERE id = ?`).get(row.id) as any;
                if (updated && updated.attempt_count >= 10) {
                  db.prepare(`UPDATE sync_outbox SET status = 'failed' WHERE id = ?`).run(row.id);
                }
              }
              abortRemainingChunks = true;
              break;
            }
          } else {
            // Token refresh failed — abort.
            for (const chunk of networkFailures) {
              for (const row of chunk) {
                db.prepare(`
                  UPDATE sync_outbox
                  SET attempt_count = attempt_count + 1,
                      error_message = ?,
                      last_attempted_at = datetime('now')
                  WHERE id = ?
                `).run('Auth failed. Check Sync Device Secret.', row.id);
              }
            }
            abortRemainingChunks = true;
          }
        }
      }

      // ---- Phase 2: single-row fallback for chunks the batch couldn't take ----
      for (const chunk of fallbackChunks) {
        if (abortRemainingChunks) break;

        for (const row of chunk) {
          let networkError = false;
          let dbAlreadyUpdated = false;
          let parsedPayload: any;
          try {
            parsedPayload = JSON.parse(row.payload);
          } catch (parseErr: any) {
            db.prepare(`UPDATE sync_outbox SET status = 'failed', error_message = ? WHERE id = ?`)
              .run(`Corrupt payload: ${parseErr?.message || parseErr}`, row.id);
            continue;
          }

          try {
            let response: Response;
            try {
              response = await fetchWithTimeout(`${apiUrl}/sync/ingest`, {
                method: 'POST',
                headers: syncHeaders as Record<string, string>,
                body: JSON.stringify({
                  table: row.table_name,
                  operation: row.operation,
                  recordId: row.record_id,
                  payload: parsedPayload,
                  timestamp: row.created_at,
                  device: {
                    id: deviceInfo.deviceId,
                    name: deviceInfo.deviceName,
                    terminalNumber: deviceInfo.terminalNumber
                  }
                })
              }, 30000);
            } catch (fetchErr: any) {
              networkError = true;
              throw fetchErr;
            }

            if (response.status === 401 || response.status === 403) {
              const refreshed = await this.refreshSyncToken(deviceInfo.deviceId);
              syncHeaders = refreshed ? getSyncHeaders(deviceInfo.deviceId) : null;
              if (syncHeaders) {
                response = await fetchWithTimeout(`${apiUrl}/sync/ingest`, {
                  method: 'POST',
                  headers: syncHeaders as Record<string, string>,
                  body: JSON.stringify({
                    table: row.table_name,
                    operation: row.operation,
                    recordId: row.record_id,
                    payload: parsedPayload,
                    timestamp: row.created_at,
                    device: {
                      id: deviceInfo.deviceId,
                      name: deviceInfo.deviceName,
                      terminalNumber: deviceInfo.terminalNumber
                    }
                  })
                }, 30000);
              }
              if (!syncHeaders || response.status === 401 || response.status === 403) {
                db.prepare(`
                  UPDATE sync_outbox
                  SET attempt_count = attempt_count + 1,
                      error_message = ?,
                      last_attempted_at = datetime('now')
                  WHERE id = ?
                `).run(`Auth failed (${response.status}). Check Sync Device Secret.`, row.id);
                dbAlreadyUpdated = true;
                networkError = true;
                throw new Error(`Sync auth failed (${response.status})`);
              }
            }

            if (response.ok) {
              let result: any;
              try {
                result = await response.json();
              } catch (jsonErr: any) {
                throw new Error(`Server returned non-JSON response: ${jsonErr?.message || jsonErr}`);
              }
              const action = result?.data?.action ?? result?.action;
              const reason = result?.data?.reason ?? result?.reason ?? '';
              this.applyRowResult(row, parsedPayload, action, reason);
            } else {
              const errText = await response.text();
              if (response.status === 400 && errText.includes('Missing parent')) {
                const parentRequeued = this.requeueMissingParent(row.table_name, parsedPayload);
                db.prepare(`
                  UPDATE sync_outbox
                  SET status = 'pending',
                      attempt_count = attempt_count + 1,
                      error_message = ?,
                      last_attempted_at = datetime('now')
                  WHERE id = ?
                `).run(parentRequeued ? `Waiting for parent: ${errText.substring(0, 240)}. Parent was queued again.` : `Waiting for parent: ${errText.substring(0, 240)}`, row.id);
                continue;
              }
              const errMsg = `Server Error (${response.status}): ${errText.substring(0, 300)}`;
              db.prepare(`
                UPDATE sync_outbox
                SET attempt_count = attempt_count + 1,
                    error_message = ?,
                    last_attempted_at = datetime('now')
                WHERE id = ?
              `).run(errMsg, row.id);
              const updated = db.prepare(`SELECT attempt_count FROM sync_outbox WHERE id = ?`).get(row.id) as any;
              if (updated && updated.attempt_count >= 10) {
                db.prepare(`UPDATE sync_outbox SET status = 'failed' WHERE id = ?`).run(row.id);
              }
            }
          } catch (error: any) {
            // Skip the second DB update if the 401/403 path already wrote
            // one (this fixes the old double-increment bug that caused rows
            // to fail twice as fast under auth errors).
            if (!dbAlreadyUpdated) {
              db.prepare(`
                UPDATE sync_outbox
                SET attempt_count = attempt_count + 1,
                    error_message = ?,
                    last_attempted_at = datetime('now')
                WHERE id = ?
              `).run(error.message, row.id);
              const updated = db.prepare(`SELECT attempt_count FROM sync_outbox WHERE id = ?`).get(row.id) as any;
              if (updated && updated.attempt_count >= 10) {
                db.prepare(`UPDATE sync_outbox SET status = 'failed' WHERE id = ?`).run(row.id);
              }
            }
            if (networkError) {
              abortRemainingChunks = true;
              break;
            }
          }
        }
      }
    } catch (e) {
      console.error('Critical sync engine error:', e);
    } finally {
      this.isSyncing = false;
    }

    // Auto-rechain: if there's still pending work and we didn't bail out
    // because of a network/auth problem, kick off another cycle on the
    // next tick instead of waiting 5 seconds. This is what actually drains
    // a 21K backlog quickly — without it we cap at 1 cycle per 5 sec
    // regardless of how fast each cycle is.
    try {
      if (networkMonitor.isOnline) {
        const stillPending = db.prepare(
          `SELECT 1 FROM sync_outbox WHERE status = 'pending' LIMIT 1`
        ).get();
        if (stillPending) {
          setImmediate(() => {
            this.processPendingOutbox().catch((err) => {
              logger.warn('processPendingOutbox (rechain) failed:', err?.message || err);
            });
          });
        }
      }
    } catch {
      // Best-effort — never let the rechain check itself crash sync.
    }
  }
}
