"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
electron_1.contextBridge.exposeInMainWorld('electronAPI', {
    auth: {
        login: (credentials) => electron_1.ipcRenderer.invoke('auth:login', credentials),
        getMe: () => electron_1.ipcRenderer.invoke('auth:getMe'),
        getUsers: () => electron_1.ipcRenderer.invoke('auth:getUsers'),
        logout: () => electron_1.ipcRenderer.invoke('auth:logout'),
        verifyManagerPin: (data) => electron_1.ipcRenderer.invoke('auth:verifyManagerPin', data),
        setManagerPin: (data) => electron_1.ipcRenderer.invoke('auth:setManagerPin', data),
    },
    audit: {
        getAll: (limit) => electron_1.ipcRenderer.invoke('audit:getAll', limit),
        verifyIntegrity: () => electron_1.ipcRenderer.invoke('audit:verifyIntegrity'),
        sealLegacy: () => electron_1.ipcRenderer.invoke('audit:sealLegacy'),
    },
    products: {
        getAll: () => electron_1.ipcRenderer.invoke('products:getAll'),
        getOne: (id) => electron_1.ipcRenderer.invoke('products:getOne', id),
        create: (data) => electron_1.ipcRenderer.invoke('products:create', data),
        update: (id, data) => electron_1.ipcRenderer.invoke('products:update', id, data),
        remove: (id) => electron_1.ipcRenderer.invoke('products:remove', id),
        stockIn: (id, data) => electron_1.ipcRenderer.invoke('products:stockIn', id, data),
        getMovements: (id) => electron_1.ipcRenderer.invoke('products:getMovements', id),
    },
    inventory: {
        getSummary: () => electron_1.ipcRenderer.invoke('inventory:getSummary'),
        getLowStock: () => electron_1.ipcRenderer.invoke('inventory:getLowStock'),
        getMovements: () => electron_1.ipcRenderer.invoke('inventory:getMovements'),
        getValuation: () => electron_1.ipcRenderer.invoke('inventory:getValuation'),
        stockIn: (id, data) => electron_1.ipcRenderer.invoke('inventory:stockIn', id, data),
        stockOut: (id, data) => electron_1.ipcRenderer.invoke('inventory:stockOut', id, data),
        adjustStock: (id, data) => electron_1.ipcRenderer.invoke('inventory:adjustStock', id, data),
        addWastage: (id, data) => electron_1.ipcRenderer.invoke('inventory:addWastage', id, data),
    },
    suppliers: {
        getAll: () => electron_1.ipcRenderer.invoke('suppliers:getAll'),
        create: (data) => electron_1.ipcRenderer.invoke('suppliers:create', data),
        update: (id, data) => electron_1.ipcRenderer.invoke('suppliers:update', id, data),
        collectMilk: (data) => electron_1.ipcRenderer.invoke('suppliers:collectMilk', data),
        collectPayment: (id, data) => electron_1.ipcRenderer.invoke('suppliers:collectPayment', id, data),
        getCollections: (filters) => electron_1.ipcRenderer.invoke('suppliers:getCollections', filters),
        getLedger: (id) => electron_1.ipcRenderer.invoke('suppliers:getLedger', id),
        getCycleReport: (filters) => electron_1.ipcRenderer.invoke('suppliers:getCycleReport', filters),
        getCycleStatement: (filters) => electron_1.ipcRenderer.invoke('suppliers:getCycleStatement', filters),
    },
    customers: {
        getAll: (filters) => electron_1.ipcRenderer.invoke('customers:getAll', filters),
        getOne: (id) => electron_1.ipcRenderer.invoke('customers:getOne', id),
        create: (data) => electron_1.ipcRenderer.invoke('customers:create', data),
        update: (id, data) => electron_1.ipcRenderer.invoke('customers:update', id, data),
        remove: (id) => electron_1.ipcRenderer.invoke('customers:remove', id),
        getLedger: (id) => electron_1.ipcRenderer.invoke('customers:getLedger', id),
        collectPayment: (id, data) => electron_1.ipcRenderer.invoke('customers:collectPayment', id, data),
        search: (query) => electron_1.ipcRenderer.invoke('customers:search', query),
        getStatement: (id, startDate, endDate) => electron_1.ipcRenderer.invoke('customers:getStatement', id, startDate, endDate),
    },
    sales: {
        create: (data) => electron_1.ipcRenderer.invoke('sales:create', data),
        getAll: (filters) => electron_1.ipcRenderer.invoke('sales:getAll', filters),
        getOne: (id) => electron_1.ipcRenderer.invoke('sales:getOne', id),
        getReceipt: (id) => electron_1.ipcRenderer.invoke('sales:getReceipt', id),
        void: (data) => electron_1.ipcRenderer.invoke('sales:void', data),
        hold: (data) => electron_1.ipcRenderer.invoke('sales:hold', data),
        getHeld: () => electron_1.ipcRenderer.invoke('sales:getHeld'),
        deleteHeld: (id) => electron_1.ipcRenderer.invoke('sales:deleteHeld', id),
    },
    returns: {
        getAll: (filters) => electron_1.ipcRenderer.invoke('returns:getAll', filters),
        getSaleForReturn: (saleIdOrBillNumber) => electron_1.ipcRenderer.invoke('returns:getSaleForReturn', saleIdOrBillNumber),
        create: (data) => electron_1.ipcRenderer.invoke('returns:create', data),
    },
    receiptAudit: {
        preview: (data) => electron_1.ipcRenderer.invoke('receiptAudit:preview', data),
        save: (data) => electron_1.ipcRenderer.invoke('receiptAudit:save', data),
        getHistory: (limit) => electron_1.ipcRenderer.invoke('receiptAudit:getHistory', limit),
        getLatestForDate: (date) => electron_1.ipcRenderer.invoke('receiptAudit:getLatestForDate', date),
    },
    expenses: {
        getAll: (filters) => electron_1.ipcRenderer.invoke('expenses:getAll', filters),
        create: (data) => electron_1.ipcRenderer.invoke('expenses:create', data),
        update: (id, data) => electron_1.ipcRenderer.invoke('expenses:update', id, data),
        remove: (id) => electron_1.ipcRenderer.invoke('expenses:remove', id),
        getSummary: () => electron_1.ipcRenderer.invoke('expenses:getSummary'),
    },
    reports: {
        getDailySummary: (date) => electron_1.ipcRenderer.invoke('reports:getDailySummary', date),
        getEndOfDay: (date) => electron_1.ipcRenderer.invoke('reports:getEndOfDay', date),
        getZReport: (date) => electron_1.ipcRenderer.invoke('reports:getZReport', date),
        getSalesChart: (days) => electron_1.ipcRenderer.invoke('reports:getSalesChart', days),
        getProductPerformance: () => electron_1.ipcRenderer.invoke('reports:getProductPerformance'),
        getDashboardStats: () => electron_1.ipcRenderer.invoke('reports:getDashboardStats'),
        closeRegister: (data) => electron_1.ipcRenderer.invoke('reports:closeRegister', data),
        getCustomerDues: () => electron_1.ipcRenderer.invoke('reports:getCustomerDues'),
        getProfitLoss: (startDate, endDate) => electron_1.ipcRenderer.invoke('reports:getProfitLoss', startDate, endDate),
        getMonthlySummary: (year) => electron_1.ipcRenderer.invoke('reports:getMonthlySummary', year),
        exportReport: (data) => electron_1.ipcRenderer.invoke('exports:report', data),
    },
    dailyRates: {
        getToday: () => electron_1.ipcRenderer.invoke('dailyRates:getToday'),
        update: (data) => electron_1.ipcRenderer.invoke('dailyRates:update', data),
    },
    cashRegister: {
        getToday: () => electron_1.ipcRenderer.invoke('cashRegister:getToday'),
        open: (data) => electron_1.ipcRenderer.invoke('cashRegister:open', data),
        close: (data) => electron_1.ipcRenderer.invoke('cashRegister:close', data),
        getHistory: () => electron_1.ipcRenderer.invoke('cashRegister:getHistory'),
    },
    shifts: {
        getCurrent: () => electron_1.ipcRenderer.invoke('shifts:getCurrent'),
        getToday: () => electron_1.ipcRenderer.invoke('shifts:getToday'),
        open: (data) => electron_1.ipcRenderer.invoke('shifts:open', data),
        close: (data) => electron_1.ipcRenderer.invoke('shifts:close', data),
        getHistory: (limit) => electron_1.ipcRenderer.invoke('shifts:getHistory', limit),
    },
    settings: {
        getAll: () => electron_1.ipcRenderer.invoke('settings:getAll'),
        update: (data) => electron_1.ipcRenderer.invoke('settings:update', data),
    },
    sync: {
        getStatus: () => electron_1.ipcRenderer.invoke('sync:getStatus'),
        syncNow: () => electron_1.ipcRenderer.invoke('sync:syncNow'),
        getPendingCount: () => electron_1.ipcRenderer.invoke('sync:getPendingCount'),
    },
    system: {
        backup: () => electron_1.ipcRenderer.invoke('system:backup'),
        restore: () => electron_1.ipcRenderer.invoke('system:restore'),
        listBackups: () => electron_1.ipcRenderer.invoke('system:listBackups'),
        openBackupFolder: () => electron_1.ipcRenderer.invoke('system:openBackupFolder'),
        getPaths: () => electron_1.ipcRenderer.invoke('system:getPaths'),
        getBusinessDate: () => electron_1.ipcRenderer.invoke('system:getBusinessDate'),
    },
    printer: {
        getPrinters: () => electron_1.ipcRenderer.invoke('printer:getPrinters'),
        printReceipt: (receiptData) => electron_1.ipcRenderer.invoke('printer:printReceipt', receiptData),
        printStatement: (statementData) => electron_1.ipcRenderer.invoke('printer:printStatement', statementData),
    },
    onNetworkChange: (callback) => {
        electron_1.ipcRenderer.on('network-status-changed', (_event, status) => callback(status));
    },
});
