ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'SHOPPING_BAG';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'WASHING_MATERIAL';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'ROTI';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'ELECTRICITY_BILL';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'WASA_BILL';
ALTER TYPE "ExpenseCategory" ADD VALUE IF NOT EXISTS 'GAS_BILL';
